---
title: "Lab News"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 2021

* Congratulations to Alexandros for succesfully defending his master's thesis *Host plant selection in closely related butterfly species due to reproductive interference: Modelling a tritrophic system*.

* New paper co-authored by Claus published:  
*Martinossi-Allibert I., Veller C., Ament-Velásquez S.L., Vogan A.A., Rueffler C. and Johannesson H. (2021) Invasion and maintenance of meiotic drivers in populations of ascomycete fungi. [Evolution 75: 1150-1169](https://onlinelibrary.wiley.com/doi/10.1111/evo.14214).*

### 2020

* Alexandros Bantounas starts his master's thesis. Alexandros is interested in modeling the effect of reproducitve interference on the evolution of habitat choice. His research is motivated by the biology of *Leptidea* butterflies.

* Marco Saltini joins the lab. Marco has a background in theoretical physics and is now plunging into the world of theoretical evolutionary ecology. He is interested in how ecological niche shifts can affect the potential for adaptive diversification in organims with complex life cycles.

* New paper co-authored by Claus published:  
*Ohtsuki H., Rueffler C., Wakano J.Y., Parvinen K. and Lehmann L. (2020) The components of directional and disruptive selection in heterogeneous group-structured populations. [Journal of Theoretical Biology 507: 110449](https://www.sciencedirect.com/science/article/pii/S0022519320303040).*

* New paper by Paula and Claus published:  
*Vasconcelos P. and Rueffler C. (2020) How Does Joint Evolution of Consumer Traits Affect Resource Specialization? [The American Naturalist 195: 331-348](https://www.journals.uchicago.edu/doi/abs/10.1086/706813?journalCode=an).*

### 2019

* Congratulations to Paula for receiving a [Rosemary Grant Advanced Award](https://www.evolutionsociety.org/content/society-awards-and-prizes/graduate-research-excellence-grants.html) from the Society for the Study of Evolution to work on the role of phenotypic plasticity during divergent selection driven by resource specialization.

* New paper co-authored by Claus published:  
*Martinossi-Allibert M., Rueffler C., Arnquist G., Berger D. (2019) The efficacy of good genes sexual selection under environmental change. [Proceedings of the Royal Society B 286: 20182313](https://royalsocietypublishing.org/doi/10.1098/rspb.2018.2313).*

* New preprint by Mattias and Claus:  
*Siljestam M. and Rueffler C. (2019) Heterozygote advantage can explain the extraordinary diversity of immune genes. [bioRxiv: 347344](https://www.biorxiv.org/content/10.1101/347344v3.full).*

### 2018

* A paper co-authored by Claus and his former PhD student [Hannes Svardal](https://www.uantwerpen.be/en/staff/hannes-svardal/svardal-lab/) wins the [2018 Marcus W. Feldman Prize in Theoretical Population Biology](https://www.sciencedirect.com/science/article/pii/S0040580917301892#b6).